// data.js
const data = [
    { no: 1, file: 'file1.txt', send: '2023-10-12', receive: '2023-10-13', title: 'File Title 1', time: '12:30', fileName: 'file1.txt', reference: 'Ref123', hiddenRef: 'HRef123', analyzeFiles: 'Yes', name: 'John Doe', mainContent: 'This is the main content', content: 'Sample content', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 2, file: 'file2.txt', send: '2023-11-01', receive: '2023-11-02', title: 'File Title 2', time: '14:00', fileName: 'file2.txt', reference: 'Ref456', hiddenRef: 'HRef456', analyzeFiles: 'No', name: 'Jane Smith', mainContent: 'Another main content', content: 'Additional content', blenk: '', complianceRisk: 'High', result: 'Fail' },
    { no: 3, file: 'file3.txt', send: '2023-09-15', receive: '2023-09-16', title: 'File Title 3', time: '10:45', fileName: 'file3.txt', reference: 'Ref789', hiddenRef: 'HRef789', analyzeFiles: 'Yes', name: 'Alice Johnson', mainContent: 'Main content example', content: 'Content text', blenk: '', complianceRisk: 'Medium', result: 'Pass' },
    { no: 4, file: 'file4.txt', send: '2023-08-20', receive: '2023-08-21', title: 'File Title 4', time: '09:30', fileName: 'file4.txt', reference: 'Ref012', hiddenRef: 'HRef012', analyzeFiles: 'Yes', name: 'Bob Brown', mainContent: 'Content example 4', content: 'Text content 4', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 5, file: 'file5.txt', send: '2023-07-10', receive: '2023-07-11', title: 'File Title 5', time: '15:00', fileName: 'file5.txt', reference: 'Ref345', hiddenRef: 'HRef345', analyzeFiles: 'No', name: 'Mary Lee', mainContent: 'Content for main 5', content: 'Extra content 5', blenk: '', complianceRisk: 'Medium', result: 'Fail' },
    { no: 6, file: 'file6.txt', send: '2023-06-30', receive: '2023-07-01', title: 'File Title 6', time: '13:15', fileName: 'file6.txt', reference: 'Ref678', hiddenRef: 'HRef678', analyzeFiles: 'Yes', name: 'Steve Jobs', mainContent: 'Main content 6', content: 'More sample content', blenk: '', complianceRisk: 'High', result: 'Fail' },
    { no: 7, file: 'file7.txt', send: '2023-05-22', receive: '2023-05-23', title: 'File Title 7', time: '16:45', fileName: 'file7.txt', reference: 'Ref901', hiddenRef: 'HRef901', analyzeFiles: 'Yes', name: 'Elon Musk', mainContent: 'Sample main content', content: 'Content here', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 8, file: 'file8.txt', send: '2023-04-18', receive: '2023-04-19', title: 'File Title 8', time: '08:15', fileName: 'file8.txt', reference: 'Ref234', hiddenRef: 'HRef234', analyzeFiles: 'No', name: 'Peter Pan', mainContent: 'Sample content for main', content: 'Random content', blenk: '', complianceRisk: 'Medium', result: 'Pass' },
    { no: 9, file: 'file9.txt', send: '2023-03-28', receive: '2023-03-29', title: 'File Title 9', time: '12:45', fileName: 'file9.txt', reference: 'Ref567', hiddenRef: 'HRef567', analyzeFiles: 'Yes', name: 'Megan Fox', mainContent: 'Main text content', content: 'Text sample', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 10, file: 'file10.txt', send: '2023-02-11', receive: '2023-02-12', title: 'File Title 10', time: '17:00', fileName: 'file10.txt', reference: 'Ref890', hiddenRef: 'HRef890', analyzeFiles: 'No', name: 'Bruce Wayne', mainContent: 'Content 10', content: 'Text for 10', blenk: '', complianceRisk: 'High', result: 'Fail' },
    { no: 11, file: 'file11.txt', send: '2023-01-05', receive: '2023-01-06', title: 'File Title 11', time: '09:45', fileName: 'file11.txt', reference: 'Ref011', hiddenRef: 'HRef011', analyzeFiles: 'Yes', name: 'Clark Kent', mainContent: 'Example main', content: 'Content sample', blenk: '', complianceRisk: 'Medium', result: 'Pass' },
    { no: 12, file: 'file12.txt', send: '2023-12-25', receive: '2023-12-26', title: 'File Title 12', time: '18:30', fileName: 'file12.txt', reference: 'Ref344', hiddenRef: 'HRef344', analyzeFiles: 'No', name: 'Lois Lane', mainContent: 'Christmas content', content: 'Holiday text', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 13, file: 'file13.txt', send: '2023-11-14', receive: '2023-11-15', title: 'File Title 13', time: '07:30', fileName: 'file13.txt', reference: 'Ref677', hiddenRef: 'HRef677', analyzeFiles: 'Yes', name: 'Harry Potter', mainContent: 'Magic content', content: 'Spell text', blenk: '', complianceRisk: 'High', result: 'Fail' },
    { no: 14, file: 'file14.txt', send: '2023-10-03', receive: '2023-10-04', title: 'File Title 14', time: '14:20', fileName: 'file14.txt', reference: 'Ref910', hiddenRef: 'HRef910', analyzeFiles: 'No', name: 'Hermione Granger', mainContent: 'Main magic', content: 'Study material', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 15, file: 'file15.txt', send: '2023-09-21', receive: '2023-09-22', title: 'File Title 15', time: '11:10', fileName: 'file15.txt', reference: 'Ref112', hiddenRef: 'HRef112', analyzeFiles: 'Yes', name: 'Ron Weasley', mainContent: 'Defense content', content: 'Practice notes', blenk: '', complianceRisk: 'Medium', result: 'Pass' },
    { no: 16, file: 'file16.txt', send: '2023-08-05', receive: '2023-08-06', title: 'File Title 16', time: '15:50', fileName: 'file16.txt', reference: 'Ref445', hiddenRef: 'HRef445', analyzeFiles: 'No', name: 'Albus Dumbledore', mainContent: 'Wisdom notes', content: 'History content', blenk: '', complianceRisk: 'High', result: 'Fail' },
    { no: 17, file: 'file17.txt', send: '2023-07-29', receive: '2023-07-30', title: 'File Title 17', time: '13:25', fileName: 'file17.txt', reference: 'Ref778', hiddenRef: 'HRef778', analyzeFiles: 'Yes', name: 'Severus Snape', mainContent: 'Potion studies', content: 'Advanced content', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 18, file: 'file18.txt', send: '2023-06-13', receive: '2023-06-14', title: 'File Title 18', time: '08:05', fileName: 'file18.txt', reference: 'Ref009', hiddenRef: 'HRef009', analyzeFiles: 'No', name: 'Rubeus Hagrid', mainContent: 'Creature care', content: 'Lessons text', blenk: '', complianceRisk: 'Medium', result: 'Pass' },
    { no: 19, file: 'file19.txt', send: '2023-05-17', receive: '2023-05-18', title: 'File Title 19', time: '16:00', fileName: 'file19.txt', reference: 'Ref222', hiddenRef: 'HRef222', analyzeFiles: 'Yes', name: 'Minerva McGonagall', mainContent: 'Transformation studies', content: 'Magic theory', blenk: '', complianceRisk: 'Low', result: 'Pass' },
    { no: 20, file: 'file20.txt', send: '2023-04-10', receive: '2023-04-11', title: 'File Title 20', time: '14:40', fileName: 'file20.txt', reference: 'Ref555', hiddenRef: 'HRef555', analyzeFiles: 'No', name: 'Sirius Black', mainContent: 'Content 20', content: 'Notes for 20', blenk: '', complianceRisk: 'High', result: 'Fail' },
    { no: 21, file: 'file30.txt', send: '2024-02-25', receive: '2024-02-26', title: 'File Title 30', time: '16:50', fileName: 'file30.txt', reference: 'Ref999', hiddenRef: 'HRef999', analyzeFiles: 'Yes', name: 'Charlie Brown', mainContent: 'Content for last entry', content: 'More sample content', blenk: '', complianceRisk: 'Low', result: 'Pass' }
  ];
  
  export default data;