const TeamprojectsData = [
    {
      no: 1,
      projectName: "P8 ~ P8E ADR+ Development",
      part: 1,
      status: "Setup",
      personnel: "Gildong",
      offense: 2,
      defense: 3,
      months: 3,
      progress: 80,
      issues: "2021년 3분기에 청구 예정",
    },
    {
      no: 2,
      projectName: "AP4 MTO setup and ADJ development",
      part: 1,
      status: "Production Setup",
      personnel: "Hong Ki-dong",
      offense: 8,
      defense: 10,
      months: 10,
      progress: 80,
      issues: "",
    },
    {
      no: 3,
      projectName: "XYZ Project Phase 1",
      part: 2,
      status: "Initiation",
      personnel: "Kim Yuna",
      offense: 5,
      defense: 4,
      months: 4,
      progress: 60,
      issues: "승인 대기 중",
    },
    {
      no: 4,
      projectName: "Alpha Beta Gamma Integration",
      part: 3,
      status: "Development",
      personnel: "Lee Minho",
      offense: 7,
      defense: 6,
      months: 6,
      progress: 50,
      issues: "모듈 B에서 기술적 문제 발생",
    },
    {
      no: 5,
      projectName: "Data Migration for XYZ Corp",
      part: 1,
      status: "Planning",
      personnel: "Park Jisoo",
      offense: 3,
      defense: 5,
      months: 5,
      progress: 30,
      issues: "자원 할당 필요",
    },
    {
      no: 6,
      projectName: "Mobile App Launch",
      part: 2,
      status: "Testing",
      personnel: "Choi Sooyoung",
      offense: 6,
      defense: 7,
      months: 7,
      progress: 90,
      issues: "버그 수정 진행 중",
    },
    {
      no: 7,
      projectName: "Cloud Infrastructure Setup",
      part: 3,
      status: "Deployment",
      personnel: "Kim Taehyung",
      offense: 6,
      defense: 8,
      months: 8,
      progress: 75,
      issues: "보안 검토 대기 중",
    },
  ];
  
  export default TeamprojectsData;